export const DEFAULT_LOCALE = 'en-US'

export const appCopy = {
    sessionExpiredTitle: 'Session expired',
    retrySignIn: 'Retry sign-in',
    reconnecting: 'Reconnecting…',
    dismiss: 'Dismiss',
    checkingApiConfig: 'Checking API configuration',
} as const

export const dashboardCopy = {
    title: 'Portfolio Dashboard',
    demoMode: 'Demo Mode — connect a wallet for full functionality',
    contractLabel: 'Contract',
    walletSuffix: 'Wallet',
    loadingPortfolio: 'Loading portfolio data…',
    retryLoading: 'Retry loading',
    goToLanding: 'Go to landing',
    portfolioUnavailableTitle: 'Portfolio data is unavailable',
    overviewTab: 'Overview',
    analyticsTab: 'Analytics',
    notificationsTab: 'Notifications',
    portfolioValue: 'Portfolio Value',
    lastUpdated: 'Last updated: just now',
    allocation: 'Allocation',
    rebalanceNeeded: 'Rebalance needed',
    driftMessage: 'Your portfolio has drifted from target allocation',
    estimatedGas: (xlm: string, usd: string) => `Estimated gas: ${xlm} XLM (~$${usd})`,
    estimatedTrades: (count: number, perTrade: string) =>
        `${count} estimated trade${count === 1 ? '' : 's'} @ ${perTrade} XLM each`,
    highGasWarning: 'Estimated gas is higher than usual (> 0.5 XLM). Consider fewer trades.',
    maxSlippage: (pct: number) => `Max slippage: ${pct}% — trades beyond this will be rejected`,
    executeRebalance: 'Review rebalance',
    rebalancing: 'Rebalancing…',
    connectWalletRebalance: 'Connect wallet to execute rebalance',
    createPortfolioRebalance: 'Create a real portfolio to enable rebalancing',
    createPortfolio: 'Create Portfolio',
    cloneAsNew: 'Clone as new',
    deleteMyData: 'Delete my data',
    disconnect: 'Disconnect',
    connectWallet: 'Connect Wallet',
    resetDemo: 'Reset Demo',
    balanced: 'Balanced',
    rebalance: 'Rebalance',
    newPortfolio: 'New',
    totalValue: 'Total Value',
    previewTitle: 'Review rebalance',
    previewIntro: 'Check estimated trades, slippage limits, and preconditions before submitting on-chain trades.',
    estimatedTradesSection: 'Estimated trades',
    slippageSection: 'Slippage',
    pricesSection: 'Prices',
    preconditionsSection: 'Preconditions',
    riskSection: 'Risk',
    cancel: 'Cancel',
    confirmRebalance: 'Confirm rebalance',
    noTradesPlanned: 'No trades are required at current allocations.',
    preconditionMet: 'Ready',
    preconditionBlocked: 'Blocked',
} as const

export const rebalanceHistoryCopy = {
    title: 'Rebalance history',
    subtitle: 'Recent portfolio rebalancing activities with risk management',
    exportCsv: 'Export CSV',
    loadError: 'Failed to load rebalance history',
    emptyTitle: 'No rebalancing history yet',
    emptyDetail: 'Portfolio rebalances will appear here when they occur',
    showing: (shown: number, total: number) =>
        `Showing ${shown} of ${total} rebalance${total !== 1 ? 's' : ''}`,
    legendAutomated: 'Automated',
    legendRisk: 'Risk',
    onChain: 'On-chain',
    simulated: 'Simulated',
    offChain: 'Off-chain',
} as const

export const performanceChartCopy = {
    title: 'Portfolio performance',
    demoHint: 'Connect a wallet and create a portfolio to view performance analytics',
    loadError: 'Failed to load performance data',
    emptyTitle: 'No performance data available yet',
    emptyDetail: 'Data will appear as your portfolio value changes',
    compareEnabled: 'Comparing previous period',
    compareDisabled: 'Compare previous period',
    compareUnavailable:
        'Compare mode is enabled, but there is not enough previous period data available for this timeframe.',
    days7: '7 days',
    days30: '30 days',
    days90: '90 days',
} as const

export const assetCardCopy = {
    allocation: (pct: number) => `${pct}% allocation`,
    value: 'Value',
    price: 'Price',
    target: 'Target',
    missingQuote: 'Missing quote',
    liveQuote: 'Live quote',
    fallbackPrice: 'Fallback price',
    cachedPrice: 'Cached price',
    nativeAsset: 'Native Asset',
    issuerPrefix: 'Issuer',
    updatedAgo: (seconds: number) => `Updated ${seconds}s ago`,
} as const
